In [2]:
import numpy as np

In [3]:
# BASICS

a=np.array([1,2,3])
b=np.array([[1,2,3],[1,2,3]])



print(b)

[[1 2 3]
 [1 2 3]]


In [4]:
# dimension of array
# a.ndim
b.ndim

2

In [5]:
# shape
# a.shape
b.shape

(2, 3)

In [6]:
# Get Type
# a.dtype
# b.dtype
c=np.array([1,2,3],dtype='int16')
c.dtype



dtype('int16')

In [7]:
# Get Size
a.itemsize#in bytes


8

In [8]:
# Total size
# a.size*a.itemsize
# or
a.nbytes

24

In [9]:
# Accessing specific elemments
b

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
b[1,2]

3

In [11]:
# Get a specific row
b[0,:]

array([1, 2, 3])

In [12]:
# Column
b[:,2]

array([3, 3])

In [13]:
d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
d


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
d[0,0:4:2]

array([1, 3])

In [15]:
d[1,0]=99
d

array([[ 1,  2,  3,  4,  5],
       [99,  7,  8,  9, 10]])

In [43]:
# change entire row/column
d[0,:]=6
d

array([[ 6,  6,  6,  6,  6],
       [99,  7,  8,  9, 10]])

In [16]:
d[0,:]=[1,2,3,4,5]
d

array([[ 1,  2,  3,  4,  5],
       [99,  7,  8,  9, 10]])

In [17]:
# make diff arrays
# 0's matrix
np.zeros((91,91))


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
# all 1's
np.ones((9,9),dtype='int16')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [26]:
# any other number

np.full((9,1,9),69,dtype='int16')

array([[[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]],

       [[69, 69, 69, 69, 69, 69, 69, 69, 69]]], dtype=int16)

In [28]:
z=np.array([[1,1,1,1],[1,1,1,1]])
# full_like
np.full_like(z,9)#uses z's dimensions

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [30]:
# random  number array
np.random.rand(2,2)

array([[0.46266252, 0.69091984],
       [0.5523988 , 0.80014168]])

In [33]:
np.random.random_sample(a.shape)

array([0.45557929, 0.36158982, 0.20888943])

In [63]:
# random ints
np.random.randint(-8,8,size=(3,3))

array([[-8, -8, -2],
       [ 2, -5,  1],
       [-3, -8, -8]])

In [64]:
# identity matrix
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [66]:
# repeat arrays
arr=np.array([1,2,3,4])
ar=np.repeat(arr,3)
ar

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [67]:
arr=np.array([[1,2,3,4]])
ar=np.repeat(arr,3,axis=0)
ar

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [68]:
arr=np.array([[1,2,3,4]])
ar=np.repeat(arr,3,axis=1)
ar

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]])

In [74]:
# question
aray=np.ones((5,5))
aray
zero=np.zeros((3,3))
zero[1,1]=9
zero
aray[1:4,1:4]=zero
aray

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
# c=a copys by address shound not do this
# instead-
c=a.copy()
c

array([1, 2, 3])

In [93]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6])

In [94]:
a+=2
a

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
a*2


array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [96]:
a/2

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [97]:
a**3

array([  27,   64,  125,  216,  343,  512,  729, 1000])

In [102]:
b=np.array([1,2,4,4,3,5,6,3])
b

array([1, 2, 4, 4, 3, 5, 6, 3])

In [103]:
a+b

array([ 4,  6,  9, 10, 10, 13, 15, 13])