In [8]:
import numpy as np

In [40]:
# BASICS

a=np.array([1,2,3])
b=np.array([[1,2,3],[1,2,3]])



print(b)

[[1 2 3]
 [1 2 3]]


In [20]:
# dimension of array
# a.ndim
b.ndim

2

In [22]:
# shape
# a.shape
b.shape

(2, 3)

In [26]:
# Get Type
# a.dtype
# b.dtype
c=np.array([1,2,3],dtype='int16')
c.dtype



dtype('int16')

In [27]:
# Get Size
a.itemsize#in bytes


8

In [29]:
# Total size
# a.size*a.itemsize
# or
a.nbytes

24

In [30]:
# Accessing specific elemments
b

array([[1, 2, 3],
       [1, 2, 3]])

In [31]:
b[1,2]

3

In [32]:
# Get a specific row
b[0,:]

array([1, 2, 3])

In [33]:
# Column
b[:,2]

array([3, 3])

In [34]:
d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
d


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
d[0,0:4:2]

array([1, 3])

In [42]:
d[1,0]=99
d

array([[ 1,  2,  3,  4,  5],
       [99,  7,  8,  9, 10]])

In [43]:
# change entire row/column
d[0,:]=6
d

array([[ 6,  6,  6,  6,  6],
       [99,  7,  8,  9, 10]])

In [44]:
d[0,:]=[1,2,3,4,5]
d

array([[ 1,  2,  3,  4,  5],
       [99,  7,  8,  9, 10]])

In [54]:
# make diff arrays
# 0's matrix
np.zeros((9,9))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])